# Generated by Django 2.2.6 on 2019-10-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=50)),
                ('create', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
